name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,ec2
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        options: >-
          --health-cmd="curl -f http://localhost:4566/health || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Esperar a LocalStack
        run: sleep 20

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve
